import json
rows=[{"kind":"group","text":"Ritu Ahuja 1994 Trust"}]
# (name, [income_types])
data=[
("3M COMPANY CMN",["DIVIDENDS"]),
("A.O. SMITH CORP (DEL) CMN",["DIVIDENDS"]),
("ABBOTT LABORATORIES CMN",["DIVIDENDS"]),
("ABBVIE INC CMN",["DIVIDENDS"]),
("ABIOMED, INC. CMN",["NONE"]),
("ACADIA HEALTHCARE COMPANY INC CMN",["NONE"]),
("ACCENTURE PLC CMN CLASS A",["DIVIDENDS"]),
("ACTIVISION BLIZZARD, INC CMN",["DIVIDENDS"]),
("ACUITY BRANDS, INC. CMN",["DIVIDENDS","CAPITAL GAINS"]),
("ADOBE INC CMN",["CAPITAL GAINS"]),
("ADVANCE AUTO PARTS, INC. CMN",["DIVIDENDS","CAPITAL GAINS"]),
("ADVANCED MICRO DEVICES, INC. CMN",["CAPITAL GAINS"]),
("AERCAP HOLDINGS NV ORD CMN",["NONE"]),
("AES CORP. CMN",["DIVIDENDS","CAPITAL GAINS"]),
("AFFILIATED MANAGERS GROUP INC CMN",["DIVIDENDS"]),
("AFLAC INCORPORATED CMN",["DIVIDENDS"]),
("AGILENT TECHNOLOGIES, INC. CMN",["DIVIDENDS"]),
("AGIOS PHARMACEUTICALS, INC. CMN",["NONE"]),
("AIR LEASE CORPORATION CMN",["DIVIDENDS"]),
("AIR PRODUCTS & CHEMICALS INC CMN",["DIVIDENDS"]),
("AKAMAI TECHNOLOGIES, INC. CMN",["CAPITAL GAINS"]),
("ALASKA AIR GROUP INC (DEL HLDG) CMN",["DIVIDENDS"]),
("ALBEMARLE CORP CMN",["DIVIDENDS"]),
("ALCOA CORPORATION CMN",["NONE"]),
("ALEXANDRIA REAL ESTATE EQUITIES, INC.",["DIVIDENDS","CAPITAL GAINS","PARTNERSHIP INCOME"]),
("ALEXION PHARMACEUTICALS, INC. CMN",["NONE"]),
("ALIGN TECHNOLOGY, INC CMN",["NONE"]),
("ALKERMES PLC CMN",["NONE"]),
("ALLERGAN PUBLIC LIMITED COMPAN CMN",["DIVIDENDS"]),
("ALLIANCE DATA SYSTEMS CORPORAT CMN",["DIVIDENDS"]),
("ALLSTATE CORPORATION COMMON STOCK",["DIVIDENDS"]),
("ALNYLAM PHARMACEUTICALS, INC. CMN",["NONE"]),
("ALPHABET INC. CMN CLASS A",["CAPITAL GAINS"]),
("ALPHABET INC. CMN CLASS C",["NONE"]),
("ALTRIA GROUP, INC. CMN",["DIVIDENDS"]),
("AMAZON.COM INC CMN",["CAPITAL GAINS"]),
("AMC NETWORKS INC CMN",["CAPITAL GAINS"]),
("AMCOR PLC CMN",["DIVIDENDS"]),
("AMEREN CORPORATION CMN",["DIVIDENDS"]),
("AMERICAN AIRLINES GROUP INC CMN",["DIVIDENDS","CAPITAL GAINS"]),
("AMERICAN ELECTRIC POWER INC CMN",["DIVIDENDS"]),
("AMERICAN EXPRESS CO. CMN",["DIVIDENDS","CAPITAL GAINS"]),
("AMERICAN INTL GROUP, INC. CMN",["DIVIDENDS","CAPITAL GAINS"]),
("AMERICAN TOWER CORPORATION CMN",["DIVIDENDS","PARTNERSHIP INCOME"]),
("AMERICAN WATER WORKS CO, INC. CMN",["DIVIDENDS","PARTNERSHIP INCOME"]),
("AMERIPRISE FINANCIAL, INC. CMN",["DIVIDENDS"]),
("AMERISOURCEBERGEN CORPORATION CMN",["DIVIDENDS"]),
("AMETEK INC (NEW) CMN",["DIVIDENDS"]),
("AMGEN INC. CMN",["DIVIDENDS","CAPITAL GAINS"]),
("AMPHENOL CORP CL-A (NEW) CMN CLASS A",["DIVIDENDS"]),
("ANADARKO PETROLEUM CORP CMN",["DIVIDENDS","CAPITAL GAINS"]),
("ANCHORAGE ALASKA WTR REV REV 5.000% 05/01/19 MN WTR REV RFDG BDS 2009 BEO",["INTEREST"]),
("ANSYS, INC. CMN",["NONE"]),
("ANTERO RESOURCES CORPORATION CMN",["NONE"]),
("ANTHEM, INC. CMN",["DIVIDENDS","CAPITAL GAINS"]),
("AON PLC CMN",["DIVIDENDS","CAPITAL GAINS"]),
("APACHE CORP. CMN",["DIVIDENDS"]),
]
for nm,inc in data:
    rows.append({"kind":"asset","owner":"SP","asset_name":nm,"ticker":None,"eif":None,
        "value":None,"income_types":inc,"other_income_spec":None,"amount_of_income":None,"transaction":None})
obj={"pdf_page":40,"printed_label":"Rohit Khanna 40 of 210",
"section":"Schedule A: Assets and Unearned Income","page_type":"schedule_a","filer":"Rohit Khanna",
"layout_note":"Block-split 'Type of Income' matrix page for a NEW trust 'Ritu Ahuja 1994 Trust' (fresh A-Z equity list, 3M through APACHE). This page shows ONLY the Type-of-Income block (columns: None, Dividends, Rent, Interest, Capital Gains, Excepted/Blind Trust, Tax Deferred, Partnership Income); the Value (Min/Max) and Amount-of-Income blocks are blank/on companion pages, so value and amount_of_income are null. EIF column empty. All owners SP. A row may carry multiple income-type X's. 'PARTNERSHIP INCOME' is a printed column here and recorded in income_types. Marks pixel-detected against header column centers.",
"rows":rows,"free_text":None,
"uncertainties":[
{"row":13,"field":"income_types","read":"NONE","note":"AERCAP: solid X in None; a faint speck also sits in the Capital Gains column (contradicts None) - treated as artifact, excluded"},
{"row":22,"field":"income_types","read":"DIVIDENDS","note":"ALASKA AIR: solid X in Dividends; faint speck in Capital Gains column excluded as artifact"},
{"row":26,"field":"income_types","read":"NONE","note":"ALEXION: solid X in None; faint specks in Dividends/Capital Gains/Partnership excluded as artifacts"},
{"row":38,"field":"income_types","read":"DIVIDENDS","note":"AMCOR: solid X in Dividends; faint speck in Capital Gains column excluded as artifact"},
{"row":0,"field":"group_text","read":"Ritu Ahuja 1994 Trust","note":"distinct trust from pages 037-039; year reads 1994"}
],
"page_confidence":"medium"}
json.dump(obj,open('docs/2019-2/text/page-040.json','w'),indent=1,ensure_ascii=False)
print("wrote 040:",len(rows),"rows")
